version: '3'

services:
    web:
        container_name: kabum-api
        image: python:3.6
        volumes:
            - .:/home/application/current
        working_dir: /home/application/current
        ports:
            - "5001:5000"
        depends_on:
            - cache
        command: tail -f /dev/null
        networks:
            - app-network
    cache:
        image: redis
        container_name: kabum-cache
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
